name: radius-gap
channels:
  - defaults
  - conda-forge
dependencies:
  - python >= 3.6
  - pip
  - numpy < 1.24
  - astropy
  - pandas
  - scipy
  - seaborn
  - matplotlib
  - jupyter
  - jupyterlab
  - ipython
  - exoplanet
  - pip:
    - lightkurve